pretext: Generate your Data
title: Sharif Generative AI
description: Sharif University of Technology Generative AI course
university: Sharif University of Technology
course: Generative AI course
author: Dr.Seyyede Fatemeh Seyyedsalehi

course_videos: 50+
course_duration: 50
course_lessons: 20
course_resources: 30+